services:
    Fastbolt\CommandScheduler\Command\ExecuteCommandsCommand:
        tags: [ 'console.command' ]
        arguments:
            $commandLogProvider: '@Fastbolt\CommandScheduler\Provider\CommandLogProvider'
            $commandScheduleExecutor: '@Fastbolt\CommandScheduler\Execution\CommandScheduleExecutor'

    Fastbolt\CommandScheduler\Command\ScheduleCommandsCommand:
        tags: [ 'console.command' ]
        arguments:
            $commandScheduleProvider: '@Fastbolt\CommandScheduler\Provider\CommandScheduleProvider'
            $commandLogPersister: '@Fastbolt\CommandScheduler\Persistence\CommandLogPersister'

    Fastbolt\CommandScheduler\Provider\CommandLogProvider:
        $commandLogRepository: '@Fastbolt\CommandScheduler\Repository\CommandLogRepository'

    Fastbolt\CommandScheduler\Provider\CommandScheduleProvider:
        $commandScheduleRepository: '@Fastbolt\CommandScheduler\Repository\CommandScheduleRepository'
        $commandLogProvider: '@Fastbolt\CommandScheduler\Provider\CommandLogProvider'

    Fastbolt\CommandScheduler\Repository\CommandScheduleRepository:
        arguments:
            $registry: '@doctrine'
        tags: ['doctrine.repository_service']

    Fastbolt\CommandScheduler\Repository\CommandLogRepository:
        arguments:
            $registry: '@doctrine'
        tags: ['doctrine.repository_service']

    Fastbolt\CommandScheduler\Execution\CommandScheduleExecutor:
        $lockRegistry: '@Fastbolt\CommandScheduler\Lock\LockRegistry'
        $persister: '@Fastbolt\CommandScheduler\Persistence\CommandLogPersister'

    Fastbolt\CommandScheduler\Lock\LockRegistry:
        $lockFactory: '@Symfony\Component\Lock\LockFactory'

    Fastbolt\CommandScheduler\Persistence\CommandLogPersister:
        $entityManager: '@doctrine.orm.entity_manager'
        $commandScheduleRepository: '@Fastbolt\CommandScheduler\Repository\CommandScheduleRepository'

    Fastbolt\CommandScheduler\EventSubscriber\CommandEventSubscriber:
        tags: [ 'kernel.event_subscriber' ]
        arguments:
            $commandLogRegistry: '@Fastbolt\CommandScheduler\Persistence\CommandLogRegistry'
            $commandLogPersister: '@Fastbolt\CommandScheduler\Persistence\CommandLogPersister'

    Fastbolt\CommandScheduler\Persistence\CommandLogRegistry:

    Fastbolt\CommandScheduler\Controller\ListCommandSchedulesController:
        tags: ['controller.service_arguments']
        arguments:
            $twig: '@twig'
            $commandScheduleProvider: '@Fastbolt\CommandScheduler\Provider\CommandScheduleProvider'

    Fastbolt\CommandScheduler\Controller\ListCommandLogsController:
        tags: [ 'controller.service_arguments' ]
        arguments:
            $twig: '@twig'
            $commandLogProvider: '@Fastbolt\CommandScheduler\Provider\CommandLogProvider'

    Fastbolt\CommandScheduler\Controller\ScheduleCommandController:
        tags: [ 'controller.service_arguments' ]
        arguments:
            $persister: '@Fastbolt\CommandScheduler\Persistence\CommandLogPersister'
            $router: '@router'

    Fastbolt\CommandScheduler\Controller\DashboardController:
        tags: [ 'controller.service_arguments' ]
        arguments:
            $twig: '@twig'
            $commandLogProvider: '@Fastbolt\CommandScheduler\Provider\CommandLogProvider'
            $commandScheduleProvider: '@Fastbolt\CommandScheduler\Provider\CommandScheduleProvider'
