services:
    Fastbolt\CommandScheduler\Command\ExecuteCommandsCommand:
        tags: [ 'console.command' ]
        arguments:
            $commandLogProvider: '@Fastbolt\CommandScheduler\Provider\CommandLogProvider'
            $commandScheduleExecutor: '@Fastbolt\CommandScheduler\Execution\CommandScheduleExecutor'

    Fastbolt\CommandScheduler\Command\ScheduleCommandsCommand:
        tags: [ 'console.command' ]
        arguments:
            $commandScheduleProvider: '@Fastbolt\CommandScheduler\Provider\CommandScheduleProvider'
            $commandSchedulerLogPersister: '@Fastbolt\CommandScheduler\Persistence\CommandSchedulerLogPersister'

    Fastbolt\CommandScheduler\Provider\CommandLogProvider:
        $commandLogRepository: '@Fastbolt\CommandScheduler\Repository\CommandLogRepository'

    Fastbolt\CommandScheduler\Provider\CommandScheduleProvider:
        $commandScheduleRepository: '@Fastbolt\CommandScheduler\Repository\CommandScheduleRepository'
        $commandLogProvider: '@Fastbolt\CommandScheduler\Provider\CommandLogProvider'

    Fastbolt\CommandScheduler\Repository\CommandScheduleRepository:
        $registry: '@doctrine'

    Fastbolt\CommandScheduler\Repository\CommandLogRepository:
        $registry: '@doctrine'

    Fastbolt\CommandScheduler\Execution\CommandScheduleExecutor:
        $lockRegistry: '@Fastbolt\CommandScheduler\Lock\LockRegistry'
        $persister: '@Fastbolt\CommandScheduler\Persistence\CommandSchedulerLogPersister'

    Fastbolt\CommandScheduler\Lock\LockRegistry:
        $lockFactory: '@Symfony\Component\Lock\LockFactory'

    Fastbolt\CommandScheduler\Persistence\CommandSchedulerLogPersister:
        $entityManager: '@doctrine.orm.entity_manager'
